const db = require("../util/database");

module.exports = class RekapitulasiPeminatan {
  constructor() {}

  static fetchRekapitulasiPeminatanProter() {
    return db.execute("SELECT * FROM ((SELECT pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat, pm.user, u.name as namaUser, u.ipk FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Produksi Ternak%' AND pm.urutanMinat = 1 AND u.ipk > 3.5 ORDER BY u.ipk DESC LIMIT 5) UNION (SELECT pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat, pm.user, u.name as namaUser, u.ipk FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Produksi Ternak%' AND pm.urutanMinat = 2 AND u.ipk > 3.5 ORDER BY u.ipk DESC LIMIT 5) UNION (SELECT pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat, pm.user, u.name as namaUser, u.ipk FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Produksi Ternak%' AND pm.urutanMinat = 3 AND u.ipk > 3.5 ORDER BY u.ipk DESC LIMIT 5) UNION (SELECT pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat, pm.user, u.name as namaUser, u.ipk FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Produksi Ternak%' AND pm.urutanMinat = 4 AND u.ipk > 3.5 ORDER BY u.ipk DESC LIMIT 5) UNION (SELECT pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat, pm.user, u.name as namaUser, u.ipk FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Produksi Ternak%' AND pm.urutanMinat = 5 AND u.ipk > 3.5 ORDER BY u.ipk DESC LIMIT 5)) que");
  }

  static fetchRekapitulasiPeminatanNMT() {
    return db.execute("SELECT pm.user as userId, u.name as namaMahasiswa, u.ipk as ipk, pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Nutrisi dan Makanan Ternak%' AND pm.urutanMinat = 1 AND u.ipk > 3.5 UNION SELECT pm.user as userId, u.name as namaMahasiswa, u.ipk as ipk, pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Nutrisi dan Makanan Ternak%' AND pm.urutanMinat = 2 AND u.ipk > 3.5 UNION SELECT pm.user as userId, u.name as namaMahasiswa, u.ipk as ipk, pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Nutrisi dan Makanan Ternak%' AND pm.urutanMinat = 3 AND u.ipk > 3.5 UNION SELECT pm.user as userId, u.name as namaMahasiswa, u.ipk as ipk, pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Nutrisi dan Makanan Ternak%' AND pm.urutanMinat = 4 AND u.ipk > 3.5 UNION SELECT pm.user as userId, u.name as namaMahasiswa, u.ipk as ipk, pm.idPeminatan, p.nama as namaPeminatan, pm.urutanMinat FROM nilai_matkul_peminatan_mahasiswa pm INNER JOIN users u ON pm.`user` = u.id INNER JOIN peminatan p ON pm.idPeminatan = p.id WHERE p.nama LIKE '%Nutrisi dan Makanan Ternak%' AND pm.urutanMinat = 5 AND u.ipk > 3.5");
  }
};
